[build]
builder = "NIXPACKS"
buildCommand = "npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "node dist/main"
healthcheckPath = "/api/subjects"
restartPolicyType = "ON_FAILURE"
